# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1190, 750)
        mainWindow.setStyleSheet("background-color: #EDD0D5;")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("background-color:#B7B7B7;\n"
                                 "border-radius:5px;\n"
                                 "border:2px solid #717171;")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton.setStyleSheet("background:#B7B7B7;\n"
                                      "border-radius:5px;\n"
                                      "border:2px solid #717171;\n"
                                      "font-size:17px;\n"
                                      "font-weight:bold")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_2.setStyleSheet("background:#B7B7B7;\n"
                                        "border-radius:5px;\n"
                                        "border:2px solid #717171;\n"
                                        "font-weight:bold;\n"
                                        "font-size:17px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("background-color: #E0E0DE;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 6)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 6)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("border:2px solid #717171;\n"
                                    "border-radius:5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_3.setMinimumSize(50,30)
        self.pushButton_3.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_3.setStyleSheet("background:#B7B7B7;\n"
                                        "border-radius:5px;\n"
                                        "border:2px solid #717171;\n"
                                        "font-weight:bold;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 4)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 6)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setStyleSheet("border:2px solid #717171;\n"
                                       "border-radius:5px;\n"
                                       "background-color: #E0E0DE;")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("border:2px solid #717171;\n"
                                   "border-radius:5px;\n"
                                   "background:#F1E3FA;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setStyleSheet("border:2px solid #717171;\n"
                                         "border-radius:5px;\n"
                                         "background-color: #E0E0DE;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_4.addWidget(self.textBrowser_2, 4, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 29))
        self.pushButton_4.setStyleSheet("border:2px solid #717171;\n"
                                        "border-top-left-radius:10px;\n"
                                        "border-bottom-left-radius:10px;\n"
                                        "background:#F1E3FA;\n"
                                        "font-size:15px")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 29))
        self.pushButton_5.setStyleSheet("border:2px solid #717171;\n"
                                        "border-top-right-radius:10px;\n"
                                        "border-bottom-right-radius:10px;\n"
                                        "background:#F1E3FA;\n"
                                        "font-size:15px")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 2)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(3, 2)
        self.gridLayout_4.setRowStretch(4, 20)
        self.gridLayout_4.setRowStretch(5, 2)
        self.gridLayout_4.setRowStretch(6, 20)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 4)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1190, 22))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet("background:#EBEDEA;")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setStyleSheet("background:#ffffff")
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionQKS = QtWidgets.QAction(mainWindow)
        self.actionQKS.setObjectName("actionQKS")
        self.actionHHP = QtWidgets.QAction(mainWindow)
        self.actionHHP.setObjectName("actionHHP")
        self.actionLWJ = QtWidgets.QAction(mainWindow)
        self.actionLWJ.setObjectName("actionLWJ")
        self.actionSZJ = QtWidgets.QAction(mainWindow)
        self.actionSZJ.setObjectName("actionSZJ")
        self.menu_2.addAction(self.actionQKS)
        self.menu_2.addAction(self.actionHHP)
        self.menu_2.addAction(self.actionLWJ)
        self.menu_2.addAction(self.actionSZJ)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">显示摄像头</p></body></html>"))
        self.pushButton.setText(_translate("mainWindow", "开始会议"))
        self.pushButton_2.setText(_translate("mainWindow", "选择主讲人"))
        self.pushButton_3.setText(_translate("mainWindow", "开始远程会议"))
        self.textBrowser.setHtml(_translate("mainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">欢迎使用本多人会议手势控制系统，请打开摄像头，尽量保持全身处于摄像头拍摄范围内，正对摄像头操作。</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">当前手势：无</span></p></body></html>"))
        self.label_2.setText(_translate("mainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">操作历史</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
                                                            "charset=\"utf-8\" /><style type=\"text/css\">\n "
                                                            "p, li { white-space: pre-wrap; }\n"
                                                            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                                                            "font-size:9pt; font-weight:400; font-style:normal;\">\n "
                                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                                                            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                            "style=\" font-size:11pt;\">摄像头：关闭</span></p>\n "
                                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                                                            "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                                                            "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                                                            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                            "style=\" font-size:11pt;\">人数：0</span></p>\n "
                                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                                                            "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                                                            "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                                                            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                            "style=\" font-size:11pt;\">手部：未开始检测</span></p></body></html>"))
        self.pushButton_4.setText(_translate("mainWindow", "显示状态"))
        self.pushButton_5.setText(_translate("mainWindow", "参会人员"))
        self.menu.setTitle(_translate("mainWindow", "主页面"))
        self.menu_2.setTitle(_translate("mainWindow", "开发人员"))
        self.actionQKS.setText(_translate("mainWindow", "QKS"))
        self.actionHHP.setText(_translate("mainWindow", "HHP"))
        self.actionLWJ.setText(_translate("mainWindow", "LWJ"))
        self.actionSZJ.setText(_translate("mainWindow", "SZJ"))
