class states_html:
    def __init__(self):
        pass

    def set_html_static_default(self, textBrowser_2):
        textBrowser_2.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                              "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
                              "charset=\"utf-8\" /><style type=\"text/css\">\n "
                              "p, li { white-space: pre-wrap; }\n"
                              "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                              "font-size:9pt; font-weight:400; font-style:normal;\">\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">摄像头：关闭</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">人数：0</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">手部：未开始检测</span></p></body></html>")

    def set_html_static(self, textBrowser_2):
        textBrowser_2.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                              "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
                              "charset=\"utf-8\" /><style type=\"text/css\">\n "
                              "p, li { white-space: pre-wrap; }\n"
                              "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                              "font-size:9pt; font-weight:400; font-style:normal;\">\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">摄像头：开启</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">人数：0</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">手部：未开始检测</span></p></body></html>")

    def set_html0(self, textBrowser_2):
        textBrowser_2.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                              "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
                              "charset=\"utf-8\" /><style type=\"text/css\">\n "
                              "p, li { white-space: pre-wrap; }\n"
                              "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                              "font-size:9pt; font-weight:400; font-style:normal;\">\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">摄像头：开启</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">人数：0</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">手部：开始检测</span></p></body></html>")

    def set_html1(self, textBrowser_2):
        textBrowser_2.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                              "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
                              "charset=\"utf-8\" /><style type=\"text/css\">\n "
                              "p, li { white-space: pre-wrap; }\n"
                              "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                              "font-size:9pt; font-weight:400; font-style:normal;\">\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">摄像头：开启</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">人数：1</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">手部：开始检测</span></p></body></html>")

    def set_html2(self, textBrowser_2):
        textBrowser_2.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                              "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
                              "charset=\"utf-8\" /><style type=\"text/css\">\n "
                              "p, li { white-space: pre-wrap; }\n"
                              "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                              "font-size:9pt; font-weight:400; font-style:normal;\">\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">摄像头：开启</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">人数：2</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">手部：开始检测</span></p></body></html>")

    def set_html3(self, textBrowser_2):
        textBrowser_2.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                              "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
                              "charset=\"utf-8\" /><style type=\"text/css\">\n "
                              "p, li { white-space: pre-wrap; }\n"
                              "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
                              "font-size:9pt; font-weight:400; font-style:normal;\">\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">摄像头：开启</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">人数：>=3</span></p>\n "
                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                              "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                              "-qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n "
                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                              "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                              "style=\" font-size:11pt;\">手部：开始检测</span></p></body></html>")

    def set_html10(self, textBrowser):
        pass

    def set_html11(self, textBrowser):
        textBrowser.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
            "charset=\"utf-8\" /><style type=\"text/css\">\n "
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
            "font-size:9pt; font-weight:400; font-style:normal;\">\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">欢迎使用本多人会议手势控制系统，请打开摄像头，尽量保持全身处于摄像头拍摄范围内，正对摄像头操作。</span"
            "></p>\n "
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
            "margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; "
            "font-size:10pt;\"><br /></p>\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">当前手势：点击</span></p></body></html>")

    def set_html12(self, textBrowser):
        textBrowser.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
            "charset=\"utf-8\" /><style type=\"text/css\">\n "
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
            "font-size:9pt; font-weight:400; font-style:normal;\">\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">欢迎使用本多人会议手势控制系统，请打开摄像头，尽量保持全身处于摄像头拍摄范围内，正对摄像头操作。</span"
            "></p>\n "
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
            "margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; "
            "font-size:10pt;\"><br /></p>\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">当前手势：平移</span></p></body></html>")

    def set_html13(self, textBrowser):
        textBrowser.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
            "charset=\"utf-8\" /><style type=\"text/css\">\n "
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
            "font-size:9pt; font-weight:400; font-style:normal;\">\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">欢迎使用本多人会议手势控制系统，请打开摄像头，尽量保持全身处于摄像头拍摄范围内，正对摄像头操作。</span"
            "></p>\n "
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
            "margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; "
            "font-size:10pt;\"><br /></p>\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">当前手势：缩放</span></p></body></html>")

    def set_html14(self, textBrowser):
        textBrowser.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
            "charset=\"utf-8\" /><style type=\"text/css\">\n "
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
            "font-size:9pt; font-weight:400; font-style:normal;\">\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">欢迎使用本多人会议手势控制系统，请打开摄像头，尽量保持全身处于摄像头拍摄范围内，正对摄像头操作。</span"
            "></p>\n "
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
            "margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; "
            "font-size:10pt;\"><br /></p>\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">当前手势：抓取</span></p></body></html>")

    def set_html15(self, textBrowser):
        textBrowser.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
            "charset=\"utf-8\" /><style type=\"text/css\">\n "
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
            "font-size:9pt; font-weight:400; font-style:normal;\">\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">欢迎使用本多人会议手势控制系统，请打开摄像头，尽量保持全身处于摄像头拍摄范围内，正对摄像头操作。</span"
            "></p>\n "
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
            "margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; "
            "font-size:10pt;\"><br /></p>\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">当前手势：旋转</span></p></body></html>")

    def set_html16(self, textBrowser):
        textBrowser.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
            "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta "
            "charset=\"utf-8\" /><style type=\"text/css\">\n "
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; "
            "font-size:9pt; font-weight:400; font-style:normal;\">\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">欢迎使用本多人会议手势控制系统，请打开摄像头，尽量保持全身处于摄像头拍摄范围内，正对摄像头操作。</span"
            "></p>\n "
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; "
            "margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; "
            "font-size:10pt;\"><br /></p>\n "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
            "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" "
            "font-size:10pt;\">当前手势：无</span></p></body></html>")

    def set_html21(self, textBrowser_2):
        textBrowser_2.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">参会人员一</span> <br /></p>\n"
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">参会人员二</span>    <br /> </p>\n"
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">参会人员三</span>  <br />   </p>\n"
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">参会人员四</span> <br />    </p>\n"
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">参会人员五</span>  <br />   </p>\n"
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">参会人员六</span> <br />    </p>\n"
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">参会人员七</span></p></body></html>")

    def set_html22(self, textBrowser_2):
        textBrowser_2.setHtml(
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; "
            "font-style:normal;\"> "
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; "
            "text-indent:0px;\"><span style=\" font-size:11pt;\">无参会人员</span>    </p>\n "
            "</body></html>")
